### ISSUE TITLE
System.AccessViolation when doing many matrix multiplies from NancyFX

### ISSUE THREAD

**Issue by zippy1981** [mathnet/mathnet-numerics-native#16]
I have a rest service in a self hosted nancyFX executable that does (amongst other things) multiplies a N x N matrix by a N x 10000 matrix. This generally works. However, when I throw a large amount of calls at the service I get exceptions and the service crashes. For these test calls its A 50X50 matrix against a 50x10000 matrix

I've verified that the exception occurs at this matrix multiplication.  stack trace is below. I'll work on making an example over the weekend I can share. In the mean time, is there any other information that you can use?

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indi
cation that other memory is corrupt.
   at MathNet.Numerics.Algorithms.LinearAlgebra.Mkl.SafeNativeMethods.d_matrix_multiply(Transpose transA, Transpose tran
sB, Int32 m, Int32 n, Int32 k, Double alpha, Double[] x, Double[] y, Double beta, Double[] c)
   at MathNet.Numerics.LinearAlgebra.Double.DenseMatrix.DoMultiply(Matrix`1 other, Matrix`1 result) in c:\TeamCity\build
Agent\work\d4ecde2945c804d6\src\Numerics\LinearAlgebra\Double\DenseMatrix.cs:line 513
   at MathNet.Numerics.LinearAlgebra.Generic.Matrix`1.Multiply(Matrix`1 other) in c:\TeamCity\buildAgent\work\d4ecde2945
c804d6\src\Numerics\LinearAlgebra\Generic\Matrix.Arithmetic.cs:line 587
   at RMS.Miu.EP2ELT.Lib.CorrelationService.GenerateCorrelatedStdNormMatrix(Int32 dimensions, Double& spearman, Double&
pearson) in 

+++++++++++++++++
REDACTED my code
+++++++++++++++++

   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary param
eters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.<>c__DisplayClass2.<Dispatch>b__0(Task`1 completedTask)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.<>c__DisplayClass12.<InvokeRequestLifeCycle>b__f(Task`1 t)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pip
elines)
   at Nancy.NancyEngine.HandleRequestInternal(Request request, Func`2 preRequest)
   at Nancy.NancyEngine.HandleRequest(Request request, Func`2 preRequest)
   at Nancy.Hosting.Self.NancyHost.Process(HttpListenerContext ctx)
   at Nancy.Hosting.Self.NancyHost.GotCallback(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ListenerAsyncResult.WaitCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)

   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverla
pped* pOVERLAP)
```

**Comment by cdrnet** [comment]
I have not seen this before, but it sounds a bit as if we failed to pin a memory block before passing it down to native MKL (to prevent GC from moving it around).

(I assume you have enough RAM available - a dense double 50x10000 matrix is ~4MB)

**Comment by zippy1981** [comment]
@cdrnet I have 64gb of RAM on a 24 core server. The biggest I could get my working set to was 4.3 gigs (yes I'm sure its a 64 bit process). I was using less than to gigs of ram in total.

Do you have a suggestion for diagnosing your hypothesis with Windbg or Visual studio. Is there an unmanaged exception I can break on? Meanwhile I'll try to repoduce in a simple console app that spawns many threads that do matrix multiplication. I'll also see if hosting my web service in ASP.NET fixes the issue.

**Comment by zippy1981** [comment]
@cdrnet **Update:** The problem occurs on a WIndows 2008 R2 server (24 cores 64 gigs of ram), but not on my WIndows 8.1 Dell XPS or my 4 core HP laptop. However, it does occur on a trivial example:

https://github.com/zippy1981/GridMultiply/tree/NancyFX

Running that server and hitting the http://localhost:3579/Multiplier/1 multiple times in parallel (e.g. through [fiddler](http://fiddler2.com/)) will cause a similar crash.

In the master branch of the above repo is a console app that does the same thing without NancyFX in a Parallel.For() loop. This does not crash on any box.

I will build an unpatched Windows 2008R2 VM to try to rule out hardware. I'll also try to look at what NancyFX is doing to the ThreadPool,, and the TPL Task Scheduler. I'll also brush up on my WinDbg skills.

**Comment by cdrnet** [comment]
Thanks for the repro!

I couldn't get it to crash myself yet unfortunately, neither on my W8.1 workstation (dual quad-xeons, no HT) nor on my own W2008R2 Server (dual quad-xeons as well, with HT, but with actual server hardware), although I may have failed to cause enough parallel load, especially on the server.

Just to rule out things, is the Nancy application running in full trust on your W2008R2 server?
